name = "music-downloader-cloudflare"
main = "src/worker.js"
compatibility_date = "2026-02-09"

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "music-downloader-files"
preview_bucket_name = "music-downloader-files"
